### ISSUE TITLE
Possible to add "satellizer" to the project ?

### ISSUE THREAD

**Issue by macbroadcast** [bstavroulakis/polymer-dashboard#1]
hey great project !

I am having issues starting the demo-server at port 5000, is there any workaround for this ?

Would be great if you could add https://github.com/dotch/angular-express-starter/blob/master/server/auth/auth.service.js  

Greetings

**Comment by bstavroulakis** [comment]
I added some installation notes and made the project installation easier, so there shouldn't be any more issues with that. Concerning angular express, great idea but I think it is better not to combine Polymer and Angular at this point.

**Comment by macbroadcast** [comment]
Sorry, for pointing you in the wrong direction @bstavroulakis , i was talking about something like satelizer for example.https://github.com/sahat/satellizer since polymer 0auth https://github.com/mattcooper/oauth-authenticator is outdated (used version 0.5) Thanks
