### ISSUE TITLE
Modification in the Installation notes?

### ISSUE THREAD

**Issue by ghost** [bstavroulakis/polymer-dashboard#2]
Hi, 

Not sure if its me or maybe there might need to be a modification, but I followed the instructions under the Installation Notes. 

I got the following error when I ran it on my localhost: 8080. 

![screen shot 2015-07-29 at 7 48 51 pm](https://cloud.githubusercontent.com/assets/4535163/8972833/b4f4eb0e-362b-11e5-9ac3-b934cdd588c8.png)

Any thoughts?

**Comment by macbroadcast** [comment]
hello @bstavroulakis and @mbaroi , after i stumbled across the same problem on another project, someone on facebook pointed me to this helpfull advice , could this be the problem, because i did not see a .bowerrc file in your project  :blush:
1. make a .bowerrc file http://stackoverflow.com/questions/14079833/how-to-change-bowers-default-components-folder
2. run "bower init" in the root of your project
3. add all bower packages, 
4. add ".bowerrc" and "bower.json" to git
5. people will get all dependencies by running "npm install && bower install"

**Comment by ghost** [comment]
@macbroadcast Thanks for the suggestions. I did all of that and still could not run the file. 

This is what I got when I ran npm: 

![screen shot 2015-08-01 at 1 38 44 pm](https://cloud.githubusercontent.com/assets/4535163/9022833/a99427ce-3852-11e5-90c2-0649f156d39e.png)

Any suggestions? I deleted my previous .bowerrc file and added "directory" : "public/components" in JSON format. 
Currently what my file structure looks like: 
![screen shot 2015-08-01 at 1 40 59 pm](https://cloud.githubusercontent.com/assets/4535163/9022840/0659ba96-3853-11e5-9e23-db919ff2aa03.png)

**Comment by bstavroulakis** [comment]
The folders/ files look like the polymer-dashboard-05 project (https://github.com/bstavroulakis/polymer-dashboard-0.5) and not like the polymer-dashboard project (https://github.com/bstavroulakis/polymer-dashboard).

Maybe you have to download the Polymer-Dashboard project and not the legacy one and redo the steps.

**Comment by ghost** [comment]
I deleted the previous project that I had that was using port 8080 and followed the instructions outlined by @macbroadcast  and you @bstavroulakis for polymer 1.0 and the most recent polymer dashboard github code that you have. 

This is my current folder structure and what happened after I did "node demo-server/app.js": 
![screen shot 2015-08-02 at 8 19 55 pm](https://cloud.githubusercontent.com/assets/4535163/9028834/2fe30960-3954-11e5-82f6-263762596915.png)

This is the error message that I received on the localhost:8080 on my browser: 
![screen shot 2015-08-02 at 8 20 14 pm](https://cloud.githubusercontent.com/assets/4535163/9028838/4770c536-3954-11e5-8d3c-4fbd9020f0b9.png)

I checked my JavaScript console and this is what I got: 
![screen shot 2015-08-02 at 8 36 00 pm](https://cloud.githubusercontent.com/assets/4535163/9028901/3d81dd60-3956-11e5-8b34-5569c8bb2b2b.png)

Thoughts?

**Comment by beneditobatista** [comment]
Estou com o mesmo problema. :-(

**Comment by bstavroulakis** [comment]
Thank you @rafaellucio for the updates. It seems to be working now.
