### ISSUE TITLE
Problem caused by stray " .iron-icon-1 " class

### ISSUE THREAD

**Issue by mcrayne** [bstavroulakis/polymer-dashboard#6]
What is the purpose of the class .iron-icon-0 in this code segment found [here](https://github.com/bstavroulakis/polymer-dashboard/blob/master/app/components/pd-list/pd-list-item.html)

`.pd-list-item iron-icon.iron-icon-0 {
          position: absolute;
          top: 0.5em;
        }`

The reason I ask is it is causing this behavior:
![image](https://cloud.githubusercontent.com/assets/3066333/13304344/0ebfedb4-db22-11e5-8e69-e517aaf830df.png)

By changing that rule to: 

`.pd-list-item iron-icon.iron-icon-1 {
          position: absolute;
          top: 0.5em;
        }`

The view is corrected to this:

![image](https://cloud.githubusercontent.com/assets/3066333/13304506/f4c63b6a-db22-11e5-9eb4-3648ce7eb910.png)

Where does the .iron-icon-1 originate in the initial version of the source code? Deleting the ".iron-icon-0" in the source also corrects the issue. Where do you apply the .iron-icon-1 class in the original source?

Thanks - it was helpful to have go through this torture. Polymer really doesn't seem like a good choice for rapid prototyping, let alone a maintainable system.

**Comment by bstavroulakis** [comment]
Hmm, I can't seem to reproduce this
![polymerdashboard](https://cloud.githubusercontent.com/assets/180432/13381519/dca0d9ea-de66-11e5-8eef-76950ce909b9.png)

It has the iron-icon-0 class. These classes are added by Polymer.js to scope its elements.
If I add the iron-icon-1 and it has both the 0 and the 1 will that work for both of us you think?

`.pd-list-item iron-icon.iron-icon-0, .pd-list-item iron-icon.iron-icon-1 { position: absolute; top: 0.5em; }`

**Comment by mcrayne** [comment]
Thanks. It looked liked Polymer was scoping - but I can't figure out how it happens. Actually, you don't even need the class. Its strange.
