### ISSUE TITLE
Demo doesn't load pages

### ISSUE THREAD

**Issue by ghost** [bstavroulakis/polymer-dashboard#9]

**Comment by bstavroulakis** [comment]
Thank you for pointing this out! I updated the files for the demo pages to work. However, just to keep you up to date, this project was written 2 years ago and with the Polymer 2.0 version around the corner it will definitely need a rewrite. 
Also, the build progress is kind of outdated so it would be nice to add maybe Webpack, Progressive Web App support, ES2015, ES2016 e.t.c
